name = "Volume"
type = "product_discounts"
api_version = "2022-07"

[build]
command = "npm run asbuild:release"
path = "build/release.wasm"

[ui.paths]
create = "/aovboostoffer/new"
details = "/volume/:id"
